//
// Generated file, do not edit! Created by nedtool 5.6 from msg_makeby_host.msg.
//

#ifndef __MSG_MAKEBY_HOST_M_H
#define __MSG_MAKEBY_HOST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>msg_makeby_host.msg:21</tt> by nedtool.
 * <pre>
 * message MessageMakeByHost
 * {
 *     int source;
 *     int id;
 *     //int destination;
 * }
 * </pre>
 */
class MessageMakeByHost : public ::omnetpp::cMessage
{
  protected:
    int source;
    int id;

  private:
    void copy(const MessageMakeByHost& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MessageMakeByHost&);

  public:
    MessageMakeByHost(const char *name=nullptr, short kind=0);
    MessageMakeByHost(const MessageMakeByHost& other);
    virtual ~MessageMakeByHost();
    MessageMakeByHost& operator=(const MessageMakeByHost& other);
    virtual MessageMakeByHost *dup() const override {return new MessageMakeByHost(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getId() const;
    virtual void setId(int id);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MessageMakeByHost& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MessageMakeByHost& obj) {obj.parsimUnpack(b);}


#endif // ifndef __MSG_MAKEBY_HOST_M_H

